// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LAFTests.PropertyRegistration.PropertyRegistrationSpecs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ThankYouFieldsVerification")]
    public partial class ThankYouFieldsVerificationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ThankYouFieldsVerification.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ThankYouFieldsVerification", "\tIn order to register property for Sell or Rent\r\n\tAs a User\r\n\tI want to be able t" +
                    "o view correct messages and field values on Thank You page after property regist" +
                    "ration.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_ThankYouPage001_Verify that message \"All set <FirstName>!\" should be disp" +
            "layed on Thank You page")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void PropReg_ThankYouPage001_VerifyThatMessageAllSetFirstNameShouldBeDisplayedOnThankYouPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_ThankYouPage001_Verify that message \"All set <FirstName>!\" should be disp" +
                    "layed on Thank You page", new string[] {
                        "mytag"});
#line 8
 this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I am on Prop_Listing Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgencyDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails",
                        "Urgency",
                        "FirstName",
                        "LastName",
                        "Email",
                        "Phone",
                        "customerDirectConnectAnswer",
                        "DirectConnectDetails"});
            table1.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 1",
                        "myStreet",
                        "Notlen St",
                        "Ringwood",
                        "VIC",
                        "3134",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        "",
                        "Immediately",
                        "First",
                        "Last",
                        "a@b.com",
                        "0412213456",
                        "No",
                        ""});
#line 10
 testRunner.And("I navigate to Thank You page after registering property with details", ((string)(null)), table1, "And ");
#line 14
 testRunner.Then("Message \"All set First!\" should be displayed on Thank You page with correct First" +
                    " Name.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_ThankYouPage002_Verify that message \"Your details are being reviewed now." +
            "\" should be displayed on Thank You page")]
        public virtual void PropReg_ThankYouPage002_VerifyThatMessageYourDetailsAreBeingReviewedNow_ShouldBeDisplayedOnThankYouPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_ThankYouPage002_Verify that message \"Your details are being reviewed now." +
                    "\" should be displayed on Thank You page", ((string[])(null)));
#line 16
 this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("I am on Prop_Listing Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgencyDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails",
                        "Urgency",
                        "FirstName",
                        "LastName",
                        "Email",
                        "Phone",
                        "customerDirectConnectAnswer",
                        "DirectConnectDetails"});
            table2.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 1",
                        "myStreet",
                        "Notlen St",
                        "Ringwood",
                        "VIC",
                        "3134",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        "",
                        "Immediately",
                        "First",
                        "Last",
                        "a@b.com",
                        "0412213456",
                        "No",
                        ""});
#line 18
 testRunner.And("I navigate to Thank You page after registering property with details", ((string)(null)), table2, "And ");
#line 22
 testRunner.Then("Message for customer details to be reviewed \"Your details are being reviewed now." +
                    "\" should be displayed on Thank You page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_ThankYouPage003_Verify that message \"This usually takes just a few minute" +
            "s. We\'ll send you an email when your results are ready.\" should be displayed on " +
            "Thank You page")]
        public virtual void PropReg_ThankYouPage003_VerifyThatMessageThisUsuallyTakesJustAFewMinutes_WeLlSendYouAnEmailWhenYourResultsAreReady_ShouldBeDisplayedOnThankYouPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_ThankYouPage003_Verify that message \"This usually takes just a few minute" +
                    "s. We\'ll send you an email when your results are ready.\" should be displayed on " +
                    "Thank You page", ((string[])(null)));
#line 24
 this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("I am on Prop_Listing Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgencyDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails",
                        "Urgency",
                        "FirstName",
                        "LastName",
                        "Email",
                        "Phone",
                        "customerDirectConnectAnswer",
                        "DirectConnectDetails"});
            table3.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 1",
                        "myStreet",
                        "Notlen St",
                        "Ringwood",
                        "VIC",
                        "3134",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        "",
                        "Immediately",
                        "First",
                        "Last",
                        "a@b.com",
                        "0412213456",
                        "No",
                        ""});
#line 26
 testRunner.And("I navigate to Thank You page after registering property with details", ((string)(null)), table3, "And ");
#line 30
 testRunner.Then("Message for sending results to customer email \"This usually takes just a few minu" +
                    "tes. We\'ll send you an email when your results are ready.\" should be displayed o" +
                    "n Thank You page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_ThankYouPage004_Verify Email Message on thank You Page.")]
        public virtual void PropReg_ThankYouPage004_VerifyEmailMessageOnThankYouPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_ThankYouPage004_Verify Email Message on thank You Page.", ((string[])(null)));
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("I am on Prop_Listing Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgencyDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails",
                        "Urgency",
                        "FirstName",
                        "LastName",
                        "Email",
                        "Phone",
                        "customerDirectConnectAnswer",
                        "DirectConnectDetails"});
            table4.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 1",
                        "myStreet",
                        "Notlen St",
                        "Ringwood",
                        "VIC",
                        "3134",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        "",
                        "Immediately",
                        "First",
                        "Last",
                        "a@testpqrst.com",
                        "0412213456",
                        "No",
                        ""});
#line 34
 testRunner.And("I navigate to Thank You page after registering property with details", ((string)(null)), table4, "And ");
#line 37
 testRunner.Then("Message for customer to expect email \"EXPECT ANEMAIL SENT TOa@testpqrst.com\" shou" +
                    "ld be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_ThankYouPage005_Verify Estimate Time Message on thank You Page.")]
        public virtual void PropReg_ThankYouPage005_VerifyEstimateTimeMessageOnThankYouPage_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_ThankYouPage005_Verify Estimate Time Message on thank You Page.", ((string[])(null)));
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.Given("I am on Prop_Listing Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgencyDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails",
                        "Urgency",
                        "FirstName",
                        "LastName",
                        "Email",
                        "Phone",
                        "customerDirectConnectAnswer",
                        "DirectConnectDetails"});
            table5.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 1",
                        "myStreet",
                        "Notlen St",
                        "Ringwood",
                        "VIC",
                        "3134",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        "",
                        "Immediately",
                        "First",
                        "Last",
                        "a@testpqrst.com",
                        "0412213456",
                        "No",
                        ""});
#line 42
 testRunner.And("I navigate to Thank You page after registering property with details", ((string)(null)), table5, "And ");
#line 45
 testRunner.Then("Message for time estimate \"AVERAGETIME:14 MINUTES\" should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
