// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LAFTests.PropertyRegistration.PropertyRegistrationSpecs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("UrgencyFieldsVerification")]
    public partial class UrgencyFieldsVerificationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UrgencyFieldsVerification.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UrgencyFieldsVerification", "\t\tIn order to register property for Sell or Rent\r\n\tAs a User\r\n\tI want to be able " +
                    "to proceed after selecting valid option for Agent Quality", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency001_Verify the Question for Urgency")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void PropReg_Urgency001_VerifyTheQuestionForUrgency()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency001_Verify the Question for Urgency", new string[] {
                        "mytag"});
#line 7
 this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table1.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 9
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table1, "And ");
#line 12
 testRunner.Then("Q \"When are you looking to Sell your Property?\" should be displayed for Urgency s" +
                    "election", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency002_Verify that option \"Immediately\" should be available")]
        public virtual void PropReg_Urgency002_VerifyThatOptionImmediatelyShouldBeAvailable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency002_Verify that option \"Immediately\" should be available", ((string[])(null)));
#line 14
 this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table2.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 16
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table2, "And ");
#line 19
 testRunner.Then("Option Immediately with text \"IMMEDIATELY\" should be available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency003_Verify that option \"0To3Months\" should be available")]
        public virtual void PropReg_Urgency003_VerifyThatOption0To3MonthsShouldBeAvailable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency003_Verify that option \"0To3Months\" should be available", ((string[])(null)));
#line 21
 this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table3.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 23
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table3, "And ");
#line 26
 testRunner.Then("Option ZeroToThreeMonths with text \"0-3 MONTHS\" should be available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency004_Verify that option \"3To6Months\" should be available")]
        public virtual void PropReg_Urgency004_VerifyThatOption3To6MonthsShouldBeAvailable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency004_Verify that option \"3To6Months\" should be available", ((string[])(null)));
#line 28
 this.ScenarioSetup(scenarioInfo);
#line 29
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table4.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 30
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table4, "And ");
#line 33
 testRunner.Then("Option ThreeToSixMonths with text \"3-6 MONTHS\" should be available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency005_Verify that option \"6+Months\" should be available")]
        public virtual void PropReg_Urgency005_VerifyThatOption6MonthsShouldBeAvailable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency005_Verify that option \"6+Months\" should be available", ((string[])(null)));
#line 35
 this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table5.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 37
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table5, "And ");
#line 40
 testRunner.Then("Option SixPlusMonths with text \"6+ MONTHS\" should be available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency006_Verify that link for Moving Forward should be disabled by defa" +
            "ult")]
        public virtual void PropReg_Urgency006_VerifyThatLinkForMovingForwardShouldBeDisabledByDefault()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency006_Verify that link for Moving Forward should be disabled by defa" +
                    "ult", ((string[])(null)));
#line 42
 this.ScenarioSetup(scenarioInfo);
#line 43
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table6.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 44
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table6, "And ");
#line 47
 testRunner.Then("Moving Fwd Link is displayed disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency007_Verify that Customer Details question should be displayed when" +
            " user selects \"Immediately\" option")]
        public virtual void PropReg_Urgency007_VerifyThatCustomerDetailsQuestionShouldBeDisplayedWhenUserSelectsImmediatelyOption()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency007_Verify that Customer Details question should be displayed when" +
                    " user selects \"Immediately\" option", ((string[])(null)));
#line 49
 this.ScenarioSetup(scenarioInfo);
#line 50
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table7.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 51
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table7, "And ");
#line 54
 testRunner.When("I Select Urgency option as \"Immediately\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
 testRunner.Then("Customer Details Entry question is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency008_Verify that Customer Details question should be displayed when" +
            " user selects \"0To3Months\" option")]
        public virtual void PropReg_Urgency008_VerifyThatCustomerDetailsQuestionShouldBeDisplayedWhenUserSelects0To3MonthsOption()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency008_Verify that Customer Details question should be displayed when" +
                    " user selects \"0To3Months\" option", ((string[])(null)));
#line 57
 this.ScenarioSetup(scenarioInfo);
#line 58
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table8.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 59
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table8, "And ");
#line 62
 testRunner.When("I Select Urgency option as \"ZeroToThreeMonths\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
 testRunner.Then("Customer Details Entry question is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency009_Verify that Customer Details question should be displayed when" +
            " user selects \"3To6Months\" option")]
        public virtual void PropReg_Urgency009_VerifyThatCustomerDetailsQuestionShouldBeDisplayedWhenUserSelects3To6MonthsOption()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency009_Verify that Customer Details question should be displayed when" +
                    " user selects \"3To6Months\" option", ((string[])(null)));
#line 65
 this.ScenarioSetup(scenarioInfo);
#line 66
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table9.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 67
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table9, "And ");
#line 70
 testRunner.When("I Select Urgency option as \"ThreeToSixMonths\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 71
 testRunner.Then("Customer Details Entry question is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency010_Verify that Customer Details question should be displayed when" +
            " user selects \"SixPlusMonths\" option")]
        public virtual void PropReg_Urgency010_VerifyThatCustomerDetailsQuestionShouldBeDisplayedWhenUserSelectsSixPlusMonthsOption()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency010_Verify that Customer Details question should be displayed when" +
                    " user selects \"SixPlusMonths\" option", ((string[])(null)));
#line 73
 this.ScenarioSetup(scenarioInfo);
#line 74
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table10.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 75
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table10, "And ");
#line 78
 testRunner.When("I Select Urgency option as \"SixPlusMonths\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 79
 testRunner.Then("Customer Details Entry question is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency011_Verify the color of option \"Immediately\" when it is not select" +
            "ed")]
        public virtual void PropReg_Urgency011_VerifyTheColorOfOptionImmediatelyWhenItIsNotSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency011_Verify the color of option \"Immediately\" when it is not select" +
                    "ed", ((string[])(null)));
#line 81
 this.ScenarioSetup(scenarioInfo);
#line 82
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table11.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 83
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table11, "And ");
#line 86
 testRunner.Then("Color of the Immediately option should be \"#00AEFF\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency012_Verify that color of the option \"Immediately\" changes on selec" +
            "tion.")]
        public virtual void PropReg_Urgency012_VerifyThatColorOfTheOptionImmediatelyChangesOnSelection_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency012_Verify that color of the option \"Immediately\" changes on selec" +
                    "tion.", ((string[])(null)));
#line 88
 this.ScenarioSetup(scenarioInfo);
#line 89
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table12.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 90
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table12, "And ");
#line 93
 testRunner.When("I Select Urgency option as \"Immediately\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 94
 testRunner.And("I move back to Urgency  Question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
 testRunner.Then("Color of the Immediately option should be \"#14B24B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency013_Verify the color of option \"0To3Months\" when it is not selecte" +
            "d")]
        public virtual void PropReg_Urgency013_VerifyTheColorOfOption0To3MonthsWhenItIsNotSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency013_Verify the color of option \"0To3Months\" when it is not selecte" +
                    "d", ((string[])(null)));
#line 97
 this.ScenarioSetup(scenarioInfo);
#line 98
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table13.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 99
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table13, "And ");
#line 102
 testRunner.Then("Color of the ZeroToThreeMonths option should be \"#00AEFF\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency014_Verify that color of the option \"0To3Months\" changes on select" +
            "ion.")]
        public virtual void PropReg_Urgency014_VerifyThatColorOfTheOption0To3MonthsChangesOnSelection_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency014_Verify that color of the option \"0To3Months\" changes on select" +
                    "ion.", ((string[])(null)));
#line 104
 this.ScenarioSetup(scenarioInfo);
#line 105
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table14.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 106
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table14, "And ");
#line 109
 testRunner.When("I Select Urgency option as \"ZeroToThreeMonths\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 110
 testRunner.And("I move back to Urgency  Question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 111
 testRunner.Then("Color of the ZeroToThreeMonths option should be \"#14B24B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency015_Verify the color of option \"3To6Months\" when it is not selecte" +
            "d")]
        public virtual void PropReg_Urgency015_VerifyTheColorOfOption3To6MonthsWhenItIsNotSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency015_Verify the color of option \"3To6Months\" when it is not selecte" +
                    "d", ((string[])(null)));
#line 113
 this.ScenarioSetup(scenarioInfo);
#line 114
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table15.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 115
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table15, "And ");
#line 118
 testRunner.Then("Color of the ThreeToSixMonths option should be \"#00AEFF\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency016_Verify that color of the option \"3To6Months\" changes on select" +
            "ion.")]
        public virtual void PropReg_Urgency016_VerifyThatColorOfTheOption3To6MonthsChangesOnSelection_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency016_Verify that color of the option \"3To6Months\" changes on select" +
                    "ion.", ((string[])(null)));
#line 120
 this.ScenarioSetup(scenarioInfo);
#line 121
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table16.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 122
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table16, "And ");
#line 125
 testRunner.When("I Select Urgency option as \"ThreeToSixMonths\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 126
 testRunner.And("I move back to Urgency  Question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 127
 testRunner.Then("Color of the ThreeToSixMonths option should be \"#14B24B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency017_Verify the color of option \"6+Months\" when it is not selected")]
        public virtual void PropReg_Urgency017_VerifyTheColorOfOption6MonthsWhenItIsNotSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency017_Verify the color of option \"6+Months\" when it is not selected", ((string[])(null)));
#line 129
 this.ScenarioSetup(scenarioInfo);
#line 130
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table17.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 131
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table17, "And ");
#line 134
 testRunner.Then("Color of the SixPlusMonths option should be \"#00AEFF\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency018_Verify that color of the option \"6+Months\" changes on selectio" +
            "n.")]
        public virtual void PropReg_Urgency018_VerifyThatColorOfTheOption6MonthsChangesOnSelection_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency018_Verify that color of the option \"6+Months\" changes on selectio" +
                    "n.", ((string[])(null)));
#line 136
 this.ScenarioSetup(scenarioInfo);
#line 137
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table18.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 138
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table18, "And ");
#line 141
 testRunner.When("I Select Urgency option as \"SixPlusMonths\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 142
 testRunner.And("I move back to Urgency  Question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 143
 testRunner.Then("Color of the SixPlusMonths option should be \"#14B24B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency019_Verify that link for Moving forward is displayed as enabled wh" +
            "en user moves back to Urgency selection from Customer Details")]
        public virtual void PropReg_Urgency019_VerifyThatLinkForMovingForwardIsDisplayedAsEnabledWhenUserMovesBackToUrgencySelectionFromCustomerDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency019_Verify that link for Moving forward is displayed as enabled wh" +
                    "en user moves back to Urgency selection from Customer Details", ((string[])(null)));
#line 145
 this.ScenarioSetup(scenarioInfo);
#line 146
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table19.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 147
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table19, "And ");
#line 150
 testRunner.When("I Select Urgency option as \"SixPlusMonths\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 151
 testRunner.And("I move back to Urgency  Question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 152
 testRunner.Then("Link for Moving fwd is enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PropReg_Urgency020_Verify that Specific Agencies question is displayed on clickin" +
            "g Forward link")]
        public virtual void PropReg_Urgency020_VerifyThatSpecificAgenciesQuestionIsDisplayedOnClickingForwardLink()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PropReg_Urgency020_Verify that Specific Agencies question is displayed on clickin" +
                    "g Forward link", ((string[])(null)));
#line 154
 this.ScenarioSetup(scenarioInfo);
#line 155
 testRunner.Given("I am on Prop_Rego_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Category",
                        "PropType",
                        "Beds",
                        "ApproxValue",
                        "UnitAppNo",
                        "StreetNo",
                        "Street",
                        "Suburb",
                        "State",
                        "PostCode",
                        "Leased",
                        "LeasingDetails",
                        "AgentQuality",
                        "SpecificAgency",
                        "SpecificAgenciesDetails",
                        "ContactedAgency",
                        "ContactedAgenciesDetails"});
            table20.AddRow(new string[] {
                        "Sell",
                        "House",
                        "One",
                        "LessThanTwoHunderedK",
                        "Unit 2",
                        "myStreet1",
                        "Harlem St",
                        "Inglewood",
                        "NSW",
                        "3137",
                        "MyHome",
                        "",
                        "AbilityToGetBestOutcome",
                        "No",
                        "",
                        "No",
                        ""});
#line 156
 testRunner.And("I navigate to Urgency selection section after entering details", ((string)(null)), table20, "And ");
#line 159
 testRunner.When("I Select Urgency option as \"SixPlusMonths\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 160
 testRunner.And("I move back to Urgency  Question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 161
 testRunner.And("I click on Fwd", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
 testRunner.Then("Customer Details Entry question is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
