// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LAFTests.AgentProposalForRent.AgentProposalForRentSpecs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("InspectionFrequencyFieldsVerification")]
    public partial class InspectionFrequencyFieldsVerificationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "InspectionFrequencyFieldsVerification.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "InspectionFrequencyFieldsVerification", "\tIn order to submit the proposal for Vendors\r\n\tAs an Agent\r\n\tI want to be able to" +
                    " select Inspection Frequency", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("AgentProposalForRent_InspectionFreqSelection001_Verify the Question for Inspectio" +
            "n Frequency selection")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void AgentProposalForRent_InspectionFreqSelection001_VerifyTheQuestionForInspectionFrequencySelection()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AgentProposalForRent_InspectionFreqSelection001_Verify the Question for Inspectio" +
                    "n Frequency selection", new string[] {
                        "mytag"});
#line 7
 this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("User_navigate to Agent Registration_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Interest",
                        "AgentFirstName",
                        "AgentLastName",
                        "AgentPhone",
                        "AgentMobile",
                        "AgentEmail",
                        "AgentPosition",
                        "AgencyUnitAppNo",
                        "AgencyStreetNo",
                        "AgencyStreet",
                        "AgencySuburb",
                        "AgencyState",
                        "AgencyPostCode",
                        "AgencyName",
                        "AgencyBranch",
                        "PrincipalFirstName",
                        "PrincipalLastName",
                        "PrincipalPhone",
                        "PrincipalMobile",
                        "PrincipalEmail"});
            table1.AddRow(new string[] {
                        "Rentals",
                        "First",
                        "Last",
                        "0412213456",
                        "0412213456",
                        "randomize",
                        "Sales Consultant",
                        "Unit1",
                        "testStreet",
                        "streetname",
                        "testSuburb",
                        "VIC",
                        "3081",
                        "testAgency",
                        "branch",
                        "PFirst",
                        "PLast",
                        "0412213456",
                        "0412213456",
                        "a@testing167658756.com"});
#line 9
 testRunner.And("User navigates to BeginProposal after registering agent with details", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyMgmtTeamSize",
                        "PropertyPerPropManager",
                        "Languages",
                        "EmergencyContact",
                        "LandlordInsuranceAdvice"});
            table2.AddRow(new string[] {
                        "50",
                        "10",
                        "Spanish",
                        "Yes",
                        "Yes"});
#line 12
 testRunner.When("User navigates to Inspection Frequency Selection after entering details as", ((string)(null)), table2, "When ");
#line 15
 testRunner.Then("Question \"How often do you typically run property inspections?\" is displayed for " +
                    "Inspection Frequency selection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("AgentProposalForRent_InspectionFreqSelection002_Verify that Postcode selection qu" +
            "estion is displayed when user clicks Next after selecting Inspection Frequency a" +
            "s Every 3 months")]
        public virtual void AgentProposalForRent_InspectionFreqSelection002_VerifyThatPostcodeSelectionQuestionIsDisplayedWhenUserClicksNextAfterSelectingInspectionFrequencyAsEvery3Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AgentProposalForRent_InspectionFreqSelection002_Verify that Postcode selection qu" +
                    "estion is displayed when user clicks Next after selecting Inspection Frequency a" +
                    "s Every 3 months", ((string[])(null)));
#line 17
 this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("User_navigate to Agent Registration_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Interest",
                        "AgentFirstName",
                        "AgentLastName",
                        "AgentPhone",
                        "AgentMobile",
                        "AgentEmail",
                        "AgentPosition",
                        "AgencyUnitAppNo",
                        "AgencyStreetNo",
                        "AgencyStreet",
                        "AgencySuburb",
                        "AgencyState",
                        "AgencyPostCode",
                        "AgencyName",
                        "AgencyBranch",
                        "PrincipalFirstName",
                        "PrincipalLastName",
                        "PrincipalPhone",
                        "PrincipalMobile",
                        "PrincipalEmail"});
            table3.AddRow(new string[] {
                        "Rentals",
                        "First",
                        "Last",
                        "0412213456",
                        "0412213456",
                        "randomize",
                        "Sales Consultant",
                        "Unit1",
                        "testStreet",
                        "streetname",
                        "testSuburb",
                        "VIC",
                        "3081",
                        "testAgency",
                        "branch",
                        "PFirst",
                        "PLast",
                        "0412213456",
                        "0412213456",
                        "a@testing167658756.com"});
#line 19
 testRunner.And("User navigates to BeginProposal after registering agent with details", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyMgmtTeamSize",
                        "PropertyPerPropManager",
                        "Languages",
                        "EmergencyContact",
                        "LandlordInsuranceAdvice"});
            table4.AddRow(new string[] {
                        "50",
                        "10",
                        "Spanish",
                        "Yes",
                        "Yes"});
#line 22
 testRunner.When("User navigates to Inspection Frequency Selection after entering details as", ((string)(null)), table4, "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "InspectionFrequencyPeriod"});
            table5.AddRow(new string[] {
                        "Every 3 months"});
#line 25
 testRunner.And("User clicks Next after selecting Inspection Frequency As", ((string)(null)), table5, "And ");
#line 28
 testRunner.Then("Question for Postcode selection is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("AgentProposalForRent_InspectionFreqSelection003_Verify that under Progress sectio" +
            "n, Inspection circle should be displayed as Active")]
        public virtual void AgentProposalForRent_InspectionFreqSelection003_VerifyThatUnderProgressSectionInspectionCircleShouldBeDisplayedAsActive()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AgentProposalForRent_InspectionFreqSelection003_Verify that under Progress sectio" +
                    "n, Inspection circle should be displayed as Active", ((string[])(null)));
#line 30
 this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("User_navigate to Agent Registration_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Interest",
                        "AgentFirstName",
                        "AgentLastName",
                        "AgentPhone",
                        "AgentMobile",
                        "AgentEmail",
                        "AgentPosition",
                        "AgencyUnitAppNo",
                        "AgencyStreetNo",
                        "AgencyStreet",
                        "AgencySuburb",
                        "AgencyState",
                        "AgencyPostCode",
                        "AgencyName",
                        "AgencyBranch",
                        "PrincipalFirstName",
                        "PrincipalLastName",
                        "PrincipalPhone",
                        "PrincipalMobile",
                        "PrincipalEmail"});
            table6.AddRow(new string[] {
                        "Rentals",
                        "First",
                        "Last",
                        "0412213456",
                        "0412213456",
                        "randomize",
                        "Sales Consultant",
                        "Unit1",
                        "testStreet",
                        "streetname",
                        "testSuburb",
                        "VIC",
                        "3081",
                        "testAgency",
                        "branch",
                        "PFirst",
                        "PLast",
                        "0412213456",
                        "0412213456",
                        "a@testing167658756.com"});
#line 32
 testRunner.And("User navigates to BeginProposal after registering agent with details", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyMgmtTeamSize",
                        "PropertyPerPropManager",
                        "Languages",
                        "EmergencyContact",
                        "LandlordInsuranceAdvice"});
            table7.AddRow(new string[] {
                        "50",
                        "10",
                        "Spanish",
                        "Yes",
                        "Yes"});
#line 35
 testRunner.When("User navigates to Inspection Frequency Selection after entering details as", ((string)(null)), table7, "When ");
#line 38
 testRunner.Then("Inspection circle should be displayed as Active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("AgentProposalForRent_InspectionFreqSelection004_Verify that under Progress sectio" +
            "n, Inspection circle should be displayed as Checked on navigating to next sectio" +
            "n")]
        public virtual void AgentProposalForRent_InspectionFreqSelection004_VerifyThatUnderProgressSectionInspectionCircleShouldBeDisplayedAsCheckedOnNavigatingToNextSection()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AgentProposalForRent_InspectionFreqSelection004_Verify that under Progress sectio" +
                    "n, Inspection circle should be displayed as Checked on navigating to next sectio" +
                    "n", ((string[])(null)));
#line 40
 this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.Given("User_navigate to Agent Registration_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Interest",
                        "AgentFirstName",
                        "AgentLastName",
                        "AgentPhone",
                        "AgentMobile",
                        "AgentEmail",
                        "AgentPosition",
                        "AgencyUnitAppNo",
                        "AgencyStreetNo",
                        "AgencyStreet",
                        "AgencySuburb",
                        "AgencyState",
                        "AgencyPostCode",
                        "AgencyName",
                        "AgencyBranch",
                        "PrincipalFirstName",
                        "PrincipalLastName",
                        "PrincipalPhone",
                        "PrincipalMobile",
                        "PrincipalEmail"});
            table8.AddRow(new string[] {
                        "Rentals",
                        "First",
                        "Last",
                        "0412213456",
                        "0412213456",
                        "randomize",
                        "Sales Consultant",
                        "Unit1",
                        "testStreet",
                        "streetname",
                        "testSuburb",
                        "VIC",
                        "3081",
                        "testAgency",
                        "branch",
                        "PFirst",
                        "PLast",
                        "0412213456",
                        "0412213456",
                        "a@testing167658756.com"});
#line 42
 testRunner.And("User navigates to BeginProposal after registering agent with details", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyMgmtTeamSize",
                        "PropertyPerPropManager",
                        "Languages",
                        "EmergencyContact",
                        "LandlordInsuranceAdvice"});
            table9.AddRow(new string[] {
                        "50",
                        "10",
                        "Spanish",
                        "Yes",
                        "Yes"});
#line 45
 testRunner.When("User navigates to Inspection Frequency Selection after entering details as", ((string)(null)), table9, "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "InspectionFrequencyPeriod"});
            table10.AddRow(new string[] {
                        "Every 3 months"});
#line 48
 testRunner.And("User clicks Next after selecting Inspection Frequency As", ((string)(null)), table10, "And ");
#line 51
 testRunner.Then("Inspection circle is displayed as Checked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("AgentProposalForRent_InspectionFreqSelection005_Verify options under Property Ins" +
            "pection Frequency drop down")]
        public virtual void AgentProposalForRent_InspectionFreqSelection005_VerifyOptionsUnderPropertyInspectionFrequencyDropDown()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AgentProposalForRent_InspectionFreqSelection005_Verify options under Property Ins" +
                    "pection Frequency drop down", ((string[])(null)));
#line 53
 this.ScenarioSetup(scenarioInfo);
#line 54
 testRunner.Given("User_navigate to Agent Registration_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Interest",
                        "AgentFirstName",
                        "AgentLastName",
                        "AgentPhone",
                        "AgentMobile",
                        "AgentEmail",
                        "AgentPosition",
                        "AgencyUnitAppNo",
                        "AgencyStreetNo",
                        "AgencyStreet",
                        "AgencySuburb",
                        "AgencyState",
                        "AgencyPostCode",
                        "AgencyName",
                        "AgencyBranch",
                        "PrincipalFirstName",
                        "PrincipalLastName",
                        "PrincipalPhone",
                        "PrincipalMobile",
                        "PrincipalEmail"});
            table11.AddRow(new string[] {
                        "Rentals",
                        "First",
                        "Last",
                        "0412213456",
                        "0412213456",
                        "randomize",
                        "Sales Consultant",
                        "Unit1",
                        "testStreet",
                        "streetname",
                        "testSuburb",
                        "VIC",
                        "3081",
                        "testAgency",
                        "branch",
                        "PFirst",
                        "PLast",
                        "0412213456",
                        "0412213456",
                        "a@testing167658756.com"});
#line 55
 testRunner.And("User navigates to BeginProposal after registering agent with details", ((string)(null)), table11, "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyMgmtTeamSize",
                        "PropertyPerPropManager",
                        "Languages",
                        "EmergencyContact",
                        "LandlordInsuranceAdvice"});
            table12.AddRow(new string[] {
                        "50",
                        "10",
                        "Spanish",
                        "Yes",
                        "Yes"});
#line 58
 testRunner.When("User navigates to Inspection Frequency Selection after entering details as", ((string)(null)), table12, "When ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "InspectionFrequencyPeriod"});
            table13.AddRow(new string[] {
                        "As requested"});
            table13.AddRow(new string[] {
                        "Every 3 months"});
            table13.AddRow(new string[] {
                        "Every 4 months"});
            table13.AddRow(new string[] {
                        "Every 6 months"});
            table13.AddRow(new string[] {
                        "Every 9 months"});
            table13.AddRow(new string[] {
                        "Every 12 months"});
#line 61
 testRunner.Then("Below options should be available under Inspection Frequency drop down", ((string)(null)), table13, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("AgentProposalForRent_InspectionFreqSelection006_Verify that next section is not d" +
            "isplayed when user clicks Next without selecting any valid option for Inspection" +
            " Frequency")]
        public virtual void AgentProposalForRent_InspectionFreqSelection006_VerifyThatNextSectionIsNotDisplayedWhenUserClicksNextWithoutSelectingAnyValidOptionForInspectionFrequency()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AgentProposalForRent_InspectionFreqSelection006_Verify that next section is not d" +
                    "isplayed when user clicks Next without selecting any valid option for Inspection" +
                    " Frequency", ((string[])(null)));
#line 70
 this.ScenarioSetup(scenarioInfo);
#line 71
 testRunner.Given("User_navigate to Agent Registration_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Interest",
                        "AgentFirstName",
                        "AgentLastName",
                        "AgentPhone",
                        "AgentMobile",
                        "AgentEmail",
                        "AgentPosition",
                        "AgencyUnitAppNo",
                        "AgencyStreetNo",
                        "AgencyStreet",
                        "AgencySuburb",
                        "AgencyState",
                        "AgencyPostCode",
                        "AgencyName",
                        "AgencyBranch",
                        "PrincipalFirstName",
                        "PrincipalLastName",
                        "PrincipalPhone",
                        "PrincipalMobile",
                        "PrincipalEmail"});
            table14.AddRow(new string[] {
                        "Rentals",
                        "First",
                        "Last",
                        "0412213456",
                        "0412213456",
                        "randomize",
                        "Sales Consultant",
                        "Unit1",
                        "testStreet",
                        "streetname",
                        "testSuburb",
                        "VIC",
                        "3081",
                        "testAgency",
                        "branch",
                        "PFirst",
                        "PLast",
                        "0412213456",
                        "0412213456",
                        "a@testing167658756.com"});
#line 72
 testRunner.And("User navigates to BeginProposal after registering agent with details", ((string)(null)), table14, "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyMgmtTeamSize",
                        "PropertyPerPropManager",
                        "Languages",
                        "EmergencyContact",
                        "LandlordInsuranceAdvice"});
            table15.AddRow(new string[] {
                        "50",
                        "10",
                        "Spanish",
                        "Yes",
                        "Yes"});
#line 75
 testRunner.When("User navigates to Inspection Frequency Selection after entering details as", ((string)(null)), table15, "When ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "InspectionFrequencyPeriod"});
            table16.AddRow(new string[] {
                        "Select"});
#line 78
 testRunner.And("User clicks Next after selecting Inspection Frequency As", ((string)(null)), table16, "And ");
#line 81
 testRunner.Then("Question for Postcode selection is not displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("AgentProposalForRent_InspectionFreqSelection007_Verify that Postcode selection qu" +
            "estion is displayed when user clicks Next after selecting Inspection Frequency a" +
            "s As requested")]
        public virtual void AgentProposalForRent_InspectionFreqSelection007_VerifyThatPostcodeSelectionQuestionIsDisplayedWhenUserClicksNextAfterSelectingInspectionFrequencyAsAsRequested()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("AgentProposalForRent_InspectionFreqSelection007_Verify that Postcode selection qu" +
                    "estion is displayed when user clicks Next after selecting Inspection Frequency a" +
                    "s As requested", ((string[])(null)));
#line 83
 this.ScenarioSetup(scenarioInfo);
#line 84
 testRunner.Given("User_navigate to Agent Registration_Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Interest",
                        "AgentFirstName",
                        "AgentLastName",
                        "AgentPhone",
                        "AgentMobile",
                        "AgentEmail",
                        "AgentPosition",
                        "AgencyUnitAppNo",
                        "AgencyStreetNo",
                        "AgencyStreet",
                        "AgencySuburb",
                        "AgencyState",
                        "AgencyPostCode",
                        "AgencyName",
                        "AgencyBranch",
                        "PrincipalFirstName",
                        "PrincipalLastName",
                        "PrincipalPhone",
                        "PrincipalMobile",
                        "PrincipalEmail"});
            table17.AddRow(new string[] {
                        "Rentals",
                        "First",
                        "Last",
                        "0412213456",
                        "0412213456",
                        "randomize",
                        "Sales Consultant",
                        "Unit1",
                        "testStreet",
                        "streetname",
                        "testSuburb",
                        "VIC",
                        "3081",
                        "testAgency",
                        "branch",
                        "PFirst",
                        "PLast",
                        "0412213456",
                        "0412213456",
                        "a@testing167658756.com"});
#line 85
 testRunner.And("User navigates to BeginProposal after registering agent with details", ((string)(null)), table17, "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyMgmtTeamSize",
                        "PropertyPerPropManager",
                        "Languages",
                        "EmergencyContact",
                        "LandlordInsuranceAdvice"});
            table18.AddRow(new string[] {
                        "50",
                        "10",
                        "Spanish",
                        "Yes",
                        "Yes"});
#line 88
 testRunner.When("User navigates to Inspection Frequency Selection after entering details as", ((string)(null)), table18, "When ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "InspectionFrequencyPeriod"});
            table19.AddRow(new string[] {
                        "As requested"});
#line 91
 testRunner.And("User clicks Next after selecting Inspection Frequency As", ((string)(null)), table19, "And ");
#line 94
 testRunner.Then("Question for Postcode selection is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
